### ISSUE TITLE
Excerpt not resizing on three-column format homepage on desktop only

### ISSUE THREAD

**Issue by keempoo** [aemi-dev/aemi#10]
**Describe the bug**
Meta excerpt on some page will not wrap when in 2 or 3 column boxes. Looks like the bounding box remains the size of one-column. Works fine on mobile. 

**To Reproduce**
1. Go to Appearance> Customize> Aemi> Content Loop> Post Listing Column Layout
2. Choose 2 or 3 column layout

**Expected behavior**
Excerpt text to wrap but is cut off.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10 20H2, Mac OS 10.13.1
 - Browser [e.g. chrome, safari] Chrome, Edge, Safari

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung Galaxy S10

**Additional context**
I added in Customize> Additional CSS the following code for the thumbail images to be full height:
`.site-loop .post-attachment {max-height: 100%;}`

Removing it does not fix the problem

**Comment by aemi-dev** [comment]
Hi @keempoo ,
Thanks for your accurately-described issue. 
Can you provide me a screenshot to help me fully understand the problem ?

Best Regards

**Comment by keempoo** [comment]
Sure! I also forgot to send the url, apologies
https://www.astrosalad.com/
![image](https://user-images.githubusercontent.com/47604367/106031668-23af0b80-6095-11eb-955f-7484aa21d8bc.png)

**Comment by aemi-dev** [comment]
Hello @keempoo ,

I reviewed the bug and, the fix is the following :

```css
.site-loop .post-meta {
    width: auto;
}
```

It should ensure post meta to not overflow post header in the post loop.

Tell me if you need any more help or whatever.

Kind regards,

Guillaume

**Comment by keempoo** [comment]
That does it! Thanks so much!

**Comment by aemi-dev** [comment]
Hi @keempoo ,

This issue is officially fixed in Aemi 2.0.9, please update the theme and feel free to keep me up to date if anything goes wrong.

Best Regards,

Guillaume
