### ISSUE TITLE
automatic switching from dark to light mode does not work

### ISSUE THREAD

**Issue by davidlohner** [aemi-dev/aemi#11]
**Describe the bug**
It's not possible (at least for me) to get the "auto" color scheme to work (in Safari, in Chrome it does).

**To Reproduce**
In Theme-Customizer:
1. change the theme to dark mode (works)
2. change the theme to light mode (works, but cards in content loop stay black)
3. change the theme to "auto"

**Expected behavior**
I would expect that the theme picks up the color scheme of the operating system (in my case macOS Big Sur) and changes the theme of the website to its equivalent.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (latest release)
 - Safari (does not work)
 **- in Chrome it works (!)** 
 
**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.4 (latest release)
 - Safari (does not work)

See: https://davidlohner.de

**Comment by aemi-dev** [comment]
Hi @davidlohner ,

Firstly, thanks for the detailed issue! 

I will investigate this issue soon.  I got that something was going wrong but I could not yet fix it. Don't worry, I hope fix it as soon as possible.

Best Regards,

Guillaume

**Comment by aemi-dev** [comment]
Hi @davidlohner ,

I'm pleased to be able to say that this bug has been fixed.

To give you a better understanding of the problem, I made an error with the `window.matchMedia` API and there was an other typo in the code. In fact, I don't really know how Chrome was working anyway but now, it is fixed.

Best Regards,

Guillaume
