### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by davidlohner** [aemi-dev/aemi#6]
Hi there,

I'm looking for a new lightweight theme for my WordPress site (www.davidlohner.de) – because I want to streamline my site (only blog and a portfolio). Aemi looks stunning and I really would like to use it. Can I translate this theme somehow into german? Do you (or cloud you please) provide a PO/MO-File for translation?

Best
David

**Comment by aemi-dev** [comment]
Hi David,
Glad to see your interest in Aemi theme. I think Aemi is a good choice but I'm not currently able to provide a PO/MO-File for translation. However you can translate it here : [https://translate.wordpress.org/projects/wp-themes/aemi/](https://translate.wordpress.org/projects/wp-themes/aemi/)

I'm quite sorry for not being able to help you right now. 

Best regards,
Guillaume

**Comment by davidlohner** [comment]
Hi Guillaume,

Thanks for your reply. I added some translations. I hope I got all text modules that are visible in the front-end for site visitors.

I'm not familiar with developing Wordpress Themes. Do you have to take action now checking my translations?

Best,
David

**Comment by aemi-dev** [comment]
Hi David,

Translations are open and so correctness is. I do not have to take any action about it.
Feel free to add or edit any translations on Aemi theme.

Best Regards,
Guillaume
