### ISSUE TITLE
404 on Page 

### ISSUE THREAD

**Issue by KoreGio** [aemi-dev/aemi#7]
**Describe the bug**
with this theme I become a 404 only on page.
I try another theme and there is no problem with configuration

can you help me

**Comment by aemi-dev** [comment]
Hey @KoreGio 
How did you solve the problem ?

**Comment by KoreGio** [comment]
Yes Thank you. I need to "Custom Post Types to add" for page

**Comment by aemi-dev** [comment]
Oh right,
Do you have suggestions that could have avoided you to encounter this issue?

**Comment by keempoo** [comment]
I am also having this issue. I downloaded the most recent version of the Aemi theme and compared the Page.php files. They both have in its entirety:

 `<?php

get_header();

while (have_posts())
{
    the_post();
    do_action('aemi_page_before');
    get_template_part('inc/parts/content', 'page');
}

get_footer();
`

Is this complete?

**Comment by aemi-dev** [comment]
Hi @keempoo 

As I can see in the repo, it is complete. What are you exactly looking for ?

**Comment by keempoo** [comment]
My bad, I have a different issue! All is well!

**Comment by aemi-dev** [comment]
@keempoo fine.

Have a good journey with Aemi theme !
